import Layout from '@/components/Layout'
import Head from 'next/head'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import picture from "../../public/images/profile/picture.jpeg"
import Image from 'next/image';
import AnimatedText from '@/components/Animated';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import Hire from '@/components/Hire';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from '@/components/TransitionEffect';


// const inter = Inter({ subsets: ['latin'] })
console.log("Image Path:", profilePic);
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              {/*Optimizing image component , priority , from nextjs.org next/image */}
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto lg:hidden md:inline-block md:w-full' 
              priority
              sizes="(max-width: 768px) 100vw, 
              (max-width: 1200px) 50vw,
              33vw"
              />                
            </div>
            <div>
                <AnimatedText text="Welcome " className='!text-5xl !text-left
                xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs'> 
                Welcome to my personal portfolio page, you can access detailed information.
                You can click the buttons below for Resume and Contact.
                </p>
               <div className='flex items-center self-start mt-2 lg:self-center'>
                   <Link href="/SoftwareDeveloperErenERDOĞAN.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                  hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light md:p-2 md:px-4 md:text-base' 
                  download={true}
                  >Resume <LinkArrow className={"w-6 ml-1"} />
                  </Link> <br/>
                  <Link href="mailto:eren.erdogannn@hotmail.com" target={"_blank"}
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'>Contact</Link>
                </div>
              </div>
          </div>
        </Layout>

        {/*<Hire />*/}
        <div className='absolute right-8 bottom-8 inline-block w-20 md:hidden'>
          {/*<Image src={lightBulb} alt='Codebucks' className='w-full h-auto' />*/}
        </div>
      </main>
    </>
  )
}
